config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root 'home#index'
  get 'legend', to: 'home#legend'
  get 'info', to: 'home#info'

  resources :planner, only: [:index, :show], param: :course_code do
    
  end

  get 'course/:code', to: 'courses#show', as: 'course'
  get 'unit/:code', to: 'units#show', as: 'unit'
  get 'unit/:code/courses', to: 'units#courses', as: 'unit_courses'

  namespace 'api' do
    get 'search', to: 'search#all'
    get 'search/units', to: 'search#units'
    get 'search/courses', to: 'search#courses'

    resources :courses, only: [:index, :show], param: :code do
      member do
        get :streams
      end
    end
    
    resources :units, only: [:index, :show], param: :code do
      member do
        get :courses
      end
    end

    get 'availability/unit/schema', to: 'units#availability_schema'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :streams, class_name: "Course", foreign_key: :stream_parent
  belongs_to :stream_parent, class_name: "Course", optional: true

  has_many :course_units
  has_many :units, through: :course_units

  scope :search, -> (name) { 
    where("lower(code) like ?", "%#{name.downcase}%")
    .or(where("lower(name) like ?", "%#{name.downcase}%"))
  }
end

app/models/course_unit.rb
class CourseUnit < ApplicationRecord
  belongs_to :course
  belongs_to :unit
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :course_units
  has_many :courses, through: :course_units

  has_many :unit_availabilities

  scope :search, -> (name) {
    where.not(freeform: true)
    .where("lower(code) like ?", "%#{name.downcase}%")
      .or(where("lower(name) like ?", "%#{name.downcase}%"))
      .or(where(abbrev: name.upcase))
  }
end

app/models/unit_availability.rb
class UnitAvailability < ApplicationRecord
  belongs_to :unit
end

app/controllers/api/courses_controller.rb
module Api
  class CoursesController < ApplicationController
    def index
      cache_render "courses_index", Course.all
    end

    def show
      render json: Course.find_by_code(params[:code]), include: '**', units: true
    end

    def streams
      render json: Course.find_by_code(params[:code]), streams: true
    end
  end
end

app/controllers/api/search_controller.rb
module Api
  class SearchController < ApplicationController
    def all
      courses = Course.search(params[:query]).limit(6)
      units = Unit.search(params[:query]).limit(6)

      courses = (serialize(courses).serializable_hash[:courses] || []).map { |x| x[:type] = :course; x }
      units = (serialize(units).serializable_hash[:units] || []).map { |x| x[:type] = :unit; x }

      render json: { results: (courses + units) }
    end

    def courses
      render json: Course.search(params[:query]).limit(10), root: 'results'
    end

    def units
      render json: Unit.search(params[:query]).limit(10), root: 'results'
    end
  end
end

app/controllers/api/units_controller.rb
module Api
  class UnitsController < ApplicationController
    def index
      cache_render "units_index", Unit.where.not(freeform: true), brief: true
    end

    def show
      render json: Unit.where(code: params[:code].split(','))
    end

    def courses
      render json: Unit.find_by_code(params[:code]), courses: true
    end

    # Availabilities

    def availability_schema
      dist = UnitAvailability.distinct
      render json: {
        years: dist.pluck(:year).sort,
        periods: dist.pluck(:period).sort,
        locations: dist.pluck(:location).sort
      }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  def serialize relation, options={} 
    ActiveModelSerializers::SerializableResource.new(relation, options)
  end

  # We don't want to cache _every_ response, so we're only caching the stuff we need
  # to. For example, we don't need to cache every serialized render, just the large ones.
  def cache_render key, relation, options={}
    cache = Rails.cache.fetch("curtin_courses_#{key}") do
      serialize(relation, options).as_json
    end
    render json: cache
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    @course = Course.find_by_code(params[:code])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def legend
  end

  def info
  end
end

app/controllers/planner_controller.rb
class PlannerController < ApplicationController
  def index
  end

  def show
    @course = Course.find_by_code(params[:course_code])
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def show
    @unit = Unit.find_by_code(params[:code])
  end

  def courses
    @unit = Unit.find_by_code(params[:code])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def serialize relation, options={}
    ActiveModelSerializers::SerializableResource.new(relation, options)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/planner_helper.rb
module PlannerHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/courses/show.html.erb
<h1> <%= @course.code %> - <%= @course.name %> </h1>

<p>
<i class="fas fa-book">&nbsp;</i> <a href="<%= @course.url %>" target="_blank"> Handbook </a> <br />
<% if @course.stream_parent %>
<i class="fas fa-stream">&nbsp;</i> Stream of <a href="<%= course_path(@course.stream_parent.code) %>"> <%= @course.stream_parent.code %> - <%= @course.stream_parent.name %> </a> <br />
<% end %>
<% if @course.streams.count > 0 %>
<ul class="list-group">
  <li class="list-group-item"> <span class="tip" data-toggle="tooltip" data-placement="top" title="Select a stream to see its unit breakdown."><strong>Streams</strong></span> </li>
  <% @course.streams.each do |stream| %>
    <li class="list-group-item"> <a href="<%= course_path(stream.code) %>"> <%= stream.code %> - <%= stream.name %> </a> </li>
  <% end %>
</ul>
<% end %>
<br />
<i class="fas fa-tasks">&nbsp;</i> <a href="<%= planner_path(@course.code) %>"> Go to planner </a> </i>
</p>

<%=
  react_component("UnitGraph", 
    hide_external: true,
    unit_base_url: unit_path(":code"),
    units: serialize(@course, units: true, include: '**').serializable_hash[:course][:course_units]
  ) %>

app/views/home/index.html.erb
<h1> Curtin Courses Index </h1>
<p> Welcome to the Curtin Courses Index, a consolidated application for accessing information
about Curtin University courses and units, with data scraped from the Curtin online course handbook. </p>

<p> The primary purpose of this application is to be able to see dependency graphs for units, allowing you to 
choose and plan your prerequisites without manually crawling through the handbook. </p>

<h5> This application is only for the 2020 Course Handbook </h5>
<h4> Start searching for courses and units in the search bar above </h4>
<br />
<h4> See the Legend <a href="<%= legend_path %>"> here </a> </h4>

<br />

<div class="d-flex flex-row justify-content-center">
  <div class="p-2">
    <h2> <i class="fas fa-graduation-cap">&nbsp;</i> <%= pluralize Course.count, "Course" %> </h2>
  </div>
  <div class="p-2">
    <h1> &middot; </h1>
  </div>
  <div class="p-2">
    <h2> <i class="fas fa-scroll">&nbsp;</i> <%= pluralize Unit.count, "Unit" %> </h2>
  </div>
</div>

app/views/home/info.html.erb
<h1> Curtin Courses Index </h1>

<br />
<h3> Info </h3>
This application crawls data from the <a href="http://handbook.curtin.edu.au/">Curtin Course Handbook</a>. 
Since Curtin doesn't provide an API, we parse the HTML webpages, which are occassionally malformed.
All information provided by this application is publically available in the Curtin Handbook, just put into a more digestible format. 

<br /> <br />
<h3> API </h3> 
<p>The Curtin Courses Index provides an API that you can use to get information about all of Curtin's units and courses.</p>

<p>As always, this application is provided in good faith. Information in the handbook doesn't change very often, so please cache 
your queries where possible to make this application faster for everyone, especially in the large dataset endpoints.</p>

<%
endpoints = [
  {
    category: "Search",
    endpoints: [
      { path: "/api/search", params: "?query=", example: "/api/search?query=Mech", desc: "Search for both courses and units, with up to 6 results of each." },
      { path: "/api/search/courses", params: "?query=", example: "/api/search/courses?query=Mech", desc: "Search for courses, with up to 10 results." },
      { path: "/api/search/units", params: "?query=", example: "/api/search/units?query=Mech", desc: "Search for units, with up to 10 results." }
    ]
  },
  {
    category: "Units",
    endpoints: [
      { path: "/api/units", example: "/api/units", desc: "Brief description of all units. This is a large data endpoint." },
      { path: "/api/units/:code", params: ":code", example: "/api/units/MXEN2000", desc: "Full description of a single unit, including it's prerequisites postfix expression. Multiple units can be selected by separating them via commas." },
      { path: "/api/units/:code/courses", params: ":code", example: "/api/units/MXEN2000/courses", desc: "Same as the /api/units/:code endpoint, but includes a listing of all courses this unit belongs to." }
    ]
  },
  {
    category: "Courses",
    endpoints: [
      { path: "/api/courses", example: "/api/courses", desc: "Brief description of all courses. This is a large data endpoint." },
      { path: "/api/courses/:code", params: ":code", example: "/api/courses/MDDU-MXNCS", desc: "Full description of a course, including its units and their prerequisites." },
      { path: "/api/courses/:code/streams", params: ":code", example: "/api/courses/MDDU-MXNCS/streams", desc: "Listing of the streams of a course. Note that the stream parent is listed in all other endpoints, but stream children are only listed in this one." }
    ]
  }
]
%>

<% endpoints.each do |cat| %>
<h4> <%= cat[:category] %> </h4>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Path</th>
      <th scope="col">Params</th>
      <th scope="col">Example</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
    <% cat[:endpoints].each do |ep| %>
      <tr>
        <th scope="row"><%= ep[:path] %></th>
        <td><%= ep[:params] %></td>
        <td><%= ep[:example] %></td>
        <td><%= ep[:desc] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<% end %>

app/views/home/legend.html.erb
<h1> Curtin Courses Index </h1>
<h3> Legend </h3>

<br />
<h4> Unit Graph </h4>
<p> Each collection of units has a unit graph, such as the one below. It also contains some controls </p>
<p> You can <strong>zoom in on the graph</strong>, drag nodes around, or <strong>double click</strong> a unit to bring up its own page </p>
<p> <strong>Clicking a node once</strong> allows you to select (highlight) it. Select multiple nodes by holding down control (or long-pressing on touch screens) </p>
<p>
<span style="color: purple"><strong>Purple</strong></span> nodes are regular units for completion.
<span style="color: orange"><strong>Orange</strong></span> nodes belong to an optional group of units (see the course handbook for details).<br />
<span style="color: gray"><strong>Gray</strong></span> nodes are 'external' (not in this course of study). These are by default hidden in course graphs, but can be toggled with the buttons below.<br />
<span style="color: red"><strong>Red</strong></span> nodes are rare - they represent units that are malformed in the Curtin Course handbook (<a href="<%= unit_path("CHEM3006") %>">CHEM3006</a>, for example).
</p>

<% course = Course.find_by_code("MDDU-MXNCS") %>
<h4> Example for <a href="<%= course_path(course.code) %>"><%= course.code %> (<%= course.name %>) </a></h4>
<%= 
react_component("UnitGraph",
  hide_external: true,
  unit_base_url: unit_path(":code"),
  height: '600px',
  units: serialize(course, units: true, include: '**').serializable_hash[:course][:course_units]
)
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Curtin Courses</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application' %>
    <%= stylesheet_pack_tag    'styles' %>
  </head>

  <body>
    <header class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navtoggle" aria-controls="navtoggle" aria-expanded="false" aria-label="Toggle Nav">
        <span class="navbar-toggler-icon"> </span>
      </button>
      
      <div class="collapse navbar-collapse" id="navtoggle">
        <a class="navbar-brand" href="#"> Curtin Courses Index </a>
        <div class="navbar-nav-scroll">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="<%= root_path %>"> Home </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= legend_path %>"> Legend </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= info_path %>"> API & Info </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= planner_index_path %>"> Planner </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/JacisNonsense/curtin-courses"> Github <i class="fab fa-github"> &nbsp; </i> </a>
            </li>
          </ul>
        </div>
      </div>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item"  style="width: 500px;"> 
        <%= 
        react_component("Search", {
          selectUrl: File.join(root_path, ':type/:code'),
          searchUrl: api_search_path
        }) %> </li>
      </ul>
    </header>

    <div class="container">
      <br />
      <%= yield %>
    </div>
  </body>
</html>

app/views/planner/index.html.erb
<h1> Course Planner </h1>

<h4> Please select the course you would like to plan: </h4>
<br />
<%=
react_component("Search", {
  searchUrl: api_search_courses_path,
  selectUrl: planner_path(':code')
})
%>

app/views/planner/show.html.erb
<h1> Course Planner </h1>
<h5> <%= @course.name %> </h5>

<% if @course.streams.count > 0 %>
<br />
<h4> This course has streams. Please select which stream you wish to plan </h4>
<ul class="list-group">
  <li class="list-group-item"> <span class="tip" data-toggle="tooltip" data-placement="top" title="Select a stream to see its unit breakdown."><strong>Streams</strong></span> </li>
  <% @course.streams.each do |stream| %>
    <li class="list-group-item"> <a href="<%= planner_path(stream.code) %>"> <%= stream.code %> - <%= stream.name %> </a> </li>
  <% end %>
</ul>
<% else %>

<p>

<i class="fas fa-book">&nbsp;</i> <a href="<%= @course.url %>" target="_blank"> Handbook </a> <br />
<% if @course.stream_parent %>
<i class="fas fa-stream">&nbsp;</i> Stream of <%= @course.stream_parent.code %> - <%= @course.stream_parent.name %><br />
<% end %>
<br />

<i class="fas fa-project-diagram">&nbsp;</i> <a href="<%= course_path(@course.code) %>"> Go to course page </a>
</p>

<%=
units = serialize(@course, units: true, include: '**').serializable_hash[:course][:course_units]
if @course.stream_parent
  units += serialize(@course.stream_parent, units: true, include: '**').serializable_hash[:course][:course_units]
end
react_component("Planner", {
  units: units
})
%>

<% end %>

app/views/units/courses.html.erb
<h1> <%= @unit.code %> - <%= @unit.name %> </h1>
<h3> Courses Listing </h3>

<p>
<i class="fas fa-level-up-alt">&nbsp;</i> <a href="<%= unit_path(@unit.code) %>">Back to Unit</a>
</p>

<ul class="list-group">
<% @unit.courses.each do |course| %>
  <li class="list-group-item">
    <a href="<%= course_path(course.code) %>"> <%= course.code %> - <%= course.name %> </a>
  </li>
<% end %>
</ul>

app/views/units/show.html.erb
<h1> <%= @unit.code %> - <%= @unit.name %> </h1>

<p>
<i class="fas fa-book">&nbsp;</i> <a href="<%= @unit.url %>" target="_blank"> Handbook </a> <br />
<i class="fas fa-coins">&nbsp;</i> <%= @unit.credits %> Credits <br />
<i class="fas fa-check">&nbsp;</i> Available in <%= @unit.unit_availabilities.map { |x| "#{x.year} #{x.period}" }.uniq.sort.join(", ") %> <br />
<i class="fas fa-graduation-cap"></i> <a href="<%= unit_courses_path(@unit.code) %>"><%= pluralize(@unit.courses.count, "Course") %></a> <br />
<% if @unit.error %>
<span class="tip" data-toggle="tooltip" data-placement="bottom" title="The prerequisites for this Unit are malformed in the Curtin Handbook" style="color: #bd0000">
<i class="fas fa-exclamation-triangle">&nbsp;</i> <a href="<%= @unit.url %>" style="color: #bd0000">This unit has possible errors</a> <br />
</span>
<% end %>
</p>

<%= 
  react_component("UnitGraph",
    hide_external: false,
    units: [{ unit: serialize(@unit).serializable_hash[:unit]}],
    unit_base_url: unit_path(":code")
  ) %>